### ISSUE TITLE
The implementation is supposed to be a vertical view pager instead of a recycler view

### ISSUE THREAD

**Issue by sleepylee** [smashdown/nimble-surveys#12]
Hi Jongyoung Jeong,
First of all, thanks for your interesting submission. I and the team will be in charge of evaluating your work here and will keep you updated with the Issues we're going to open. 

The first issue I caught out was on the main UI component implementation, it was vertical view pager with a full-screen display per item.

**Comment by smashdown** [comment]
Aha. Thx for the feedback.

I was guessing too that it supposed to be pager since it has page indicator. But when I got response for survey, the cover image was flat which is not fit to screen.

So, when i fix it into paging navigation what kind of scale type for the image suppose to applied?

**Comment by sleepylee** [comment]
let's make it fit the content our current view then :)
