### ISSUE TITLE
A couple of small issues/questions regarding the project structure

### ISSUE THREAD

**Issue by sleepylee** [smashdown/nimble-surveys#13]
1. GlideModule is supposed to be injected and generated just like a part of the application utility for image loading, wouldn't it be organized in a sub-directory rather than keeping it at the same level with your main Application class?

2. I think there is a small typo for naming the `di/dataModule` that violating the general naming conventions.

3. The `AppModule` tends to contain quite many different domain components, which could easily get expanded a lot when we have a more complex application, shouldn't we introduce a separate module per component domain?

4. Redundant dirty code comments could make things become very hard for reviewing properly e.g at `Survey.kt`

**Comment by sleepylee** [comment]
also, an util for adding rx disposable calls is added but not being used, instead the verbose version of disposable.add is still being used?

```
fun launch(job: () -> Disposable) {
        disposables.add(job())
    }
```

**Comment by smashdown** [comment]
Thanks for the feedback.

1. moved into utils package.
2. typo has fixed.
3. App module has separated into each modules.
4. Cleared.

about launch, been forget to use it. it's convenient wrapper for disposables.
using it now.
