### ISSUE TITLE
Is there any intention for returning boolean for initData/initViews at BaseViewModel?

### ISSUE THREAD

**Issue by sleepylee** [smashdown/nimble-surveys#14]
As far as I understand, the main purpose is to pass the bundle data over viewmodel for processing, but I'm not quite clear on why would we need to keep a boolean returning value but there was no clear intention of using? Could you please elaborate?

**Comment by smashdown** [comment]
for some situations that need to override base activity/fragment's initData or initViews.
when requirement says that when something happen, need to close the view right away.
then we can use it, continue business logics only when init steps has been succeed.

that is why it returns boolean. just to be prepared extension.
