### ISSUE TITLE
The network calls seem not optimized

### ISSUE THREAD

**Issue by sleepylee** [smashdown/nimble-surveys#16]
Supposing that we want to reload by calling to `onRefresh`, according to your current implementation there will be another auth() calls happening before making the actual Get request, in my opinion, this isn't a good approach, as the token usually have a good amount of timeout (if it's expired then we can renew), why should we hit the auth endpoints twice instead of reusing the current valid session we're having? Please correct me if I'm missing any thing.

**Comment by smashdown** [comment]
I thought thats odd too. But requirement said do not store access token, I took that approach.

And when i was trying to add access token refresh logic. The api of refreshing is same to get auth code for starting. Than i expected call refreshing token over bearer token.

So maybe the requirement was not meant to store it anywhere. Maybe in memory was ok?

Then i will fix it into the way.

**Comment by sleepylee** [comment]
I'll review the requirements again regarding the wording of it, but the ideal phrase should be not to `hardcoding it` . Will keep you updated

**Comment by sleepylee** [comment]
hi @smashdown, I double checked on the requirements and just as I remembered before, we are not telling to *not storing the token* but rather, not *hard code* it, could you please confirm if that is the same requirements you received? https://goo.gl/nXFtNF

**Comment by smashdown** [comment]
Oh  sorry. I was wrong, I misread it.
I will separate it into auth then get the surveys tomorrow.
Is that ok?

**Comment by sleepylee** [comment]
ok, we're not rushing tho 👌💤💤💤

**Comment by smashdown** [comment]
fixed
