### ISSUE TITLE
Layout designing issues

### ISSUE THREAD

**Issue by sleepylee** [smashdown/nimble-surveys#17]
1. Dimensions are not exported for further management purpose.
2. Component's style is not well organized for reusing, and inherritance or extending purpose: e.g TextView's style including color, font, text size etc...

**Comment by smashdown** [comment]
Thx. I will improve it.

**Comment by luongvo** [comment]
One more thing, why do we need both `anim` and `animator` in the same `res` folder for animation?

**Comment by smashdown** [comment]
1. done.
2. done.

for anim/animator, also cleared.
