### ISSUE TITLE
View indicator could be resolved by a lot of external library

### ISSUE THREAD

**Issue by luongvo** [smashdown/nimble-surveys#18]
There are a lot of external library for view indicator implementation, why do we need to redefine it again by `ViewIndicator` class?

**Comment by smashdown** [comment]
it's deleted. no need the view anymore since recycler view has replaced to view pager.

anyway, I've never used vertical indicator for recyclerView before.
so just wanted to see their code. and it's also good when it's not working as you expected.

**Comment by smashdown** [comment]
@luongvo ^

**Comment by sleepylee** [comment]
we shall close it 😇
