### ISSUE TITLE
Variable name is not in a consistent format

### ISSUE THREAD

**Issue by luongvo** [smashdown/nimble-surveys#20]
Some time I see you used `camelCase`, but sometime in `camel_case` https://github.com/smashdown/nimble-surveys/blob/9bd4f4671f568afca676b130bb810e23eba624f4/app/src/main/java/com/nimble/surveys/model/AccessToken.kt#L4

**Comment by smashdown** [comment]
@luongvo oops, forgot to add json props for convention.
fixed.
